"""SQLModel models for Toilet Radar database."""
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from geoalchemy2 import Geometry
from sqlmodel import Field, SQLModel
from sqlalchemy import Column, Index, text, TIMESTAMP, BigInteger
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID


class CountryCode(str, Enum):
    """Country code enumeration."""
    CH = "CH"  # Switzerland
    FR = "FR"  # France
    DE = "DE"  # Germany
    IT = "IT"  # Italy
    AT = "AT"  # Austria


class ToiletBase(SQLModel):
    """Base toilet model with common fields."""
    name: Optional[str] = Field(default=None)
    lat: Optional[float] = Field(default=None)
    lng: Optional[float] = Field(default=None)
    accessible: Optional[bool] = Field(default=None)
    open_hours: Optional[str] = Field(default=None)
    address: Optional[str] = Field(default=None)
    rating: Optional[int] = Field(default=None)
    is_free: Optional[bool] = Field(default=None)
    type: Optional[str] = Field(default=None)
    status: Optional[str] = Field(default=None)
    notes: Optional[str] = Field(default=None)
    city: Optional[str] = Field(default=None)
    country_code: Optional[CountryCode] = Field(default=None)


class ToiletLocation(ToiletBase, table=True):
    """Primary table for toilet data.

    geom is maintained by the trigger_update_toilet_location_geom database
    trigger from lat/lng; application code never writes it directly.
    The GIST index on geom (idx_toilet_location_geom) is auto-generated by
    GeoAlchemy2 — do not add an explicit Index for it.
    """
    __tablename__ = "toilet_location"
    __table_args__ = (
        Index("idx_toilet_location_country_code", "country_code"),
        Index("idx_toilet_location_country_id", "country_code", "id"),
    )

    id: UUID = Field(
        default_factory=uuid4,
        sa_column=Column("id", PostgresUUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    )
    osm_id: Optional[int] = Field(
        default=None,
        sa_column=Column("osm_id", BigInteger, unique=True, nullable=True)
    )
    created_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column("created_at", TIMESTAMP(timezone=True), server_default=text("now()"))
    )
    geom: Optional[str] = Field(
        default=None,
        sa_column=Column("geom", Geometry("POINT", srid=4326), nullable=True)
    )
